name: heartful
description: ISM OW ML Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  smooth_page_indicator: ^0.2.0
  tflite_flutter: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/

  fonts:
   - family: Raleway
     fonts:
       - asset: assets/Raleway-Black.ttf